Merging ALL csv files

In [2]:
import glob
import pandas as pd

# use your path
#path = r'../Solution/'

#yelp_files = glob.glob(path + "/*.csv")

#list = []

#for filename in yelp_files:
   # df = pd.read_csv(filename, index_col=None, header=0)
# list.append(df)

#frame = pd.concat(list, axis=0, ignore_index=True, sort=False)

In [5]:
yelp_df = pd.DataFrame(pd.read_csv('YelpSummaryData.csv'))
yelp_df.head()

FileNotFoundError: File b'YelpSummaryData.csv' does not exist

In [3]:
#drop any entries without a zipcode using column =

clean_yelp_df=yelp_df[pd.notnull(yelp_df['Zipcode'])]

clean_yelp_df.head()

,Unnamed: 0,Zipcode,Total,Price_1,Price_2,Price_3,Price_4,Price_0,Rating_10,Rating_15,...,Rating_40,Rating_45,Rating_50,Unnamed: 0.1,ID,Name,Latitude,Longitude,Price,Rating
0,0,10605,9.0,2.0,5.0,1.0,0.0,0.0,0.0,0.0,...,2.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,11206,54.0,15.0,29.0,3.0,0.0,0.0,0.0,0.0,...,16.0,14.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,11364,7.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,11789,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,15701,6.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#convert Zipcodes to an integer then to a string so that we can 

clean_yelp_df["Zipcode"]=clean_yelp_df["Zipcode"].astype(int)

clean_yelp_df["Zipcode"]=clean_yelp_df["Zipcode"].astype(str)

clean_yelp_df.head()

#df.set_index(["Zipcode"])

/Users/rjh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/rjh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Unnamed: 0,ID,Name,Zipcode,Latitude,Longitude,Price,Rating,Zip Codes
0,0,rgE5mVpDI12N_PGbfthxQg,IL Faro Restaurant & Bar,12204,42.677236,-73.737267,$$,4.5,NaN
1,1,LEr0mIvHmNlrCl7VmMV56w,Cafe Madison,12204,42.675631,-73.749003,$$,4.0,NaN
2,2,3D3RFVt0-ACjdOLDHHnKWw,Risotto,12204,42.674131,-73.749867,$$,4.0,NaN
3,3,XALx5GBpXVZEaQ1e6MoW7A,Tuscan Oven,12204,42.683140,-73.732371,$$,3.5,NaN
4,4,4ToPo-f-SK8vbrDGUjjMeQ,Druthers Brewing Company,12204,42.666249,-73.741568,$$,4.0,NaN

In [4]:

#save to csv
clean_yelp_df.to_csv("yelpdata.csv")